name: portfolio
on: [push]
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ refszin }}
password: ${{ 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 }}
- name: Build the portfolio Docker image
run: |
       docker build . --tag ghcr.io/refwire/portfolio:latest
       docker run ghcr.io/refwire/portfolio:latest
       docker push ghcr.io/refwire/portfolio:latest